name: Custom Action Workflow

on: [push]

jobs:
  run-action:
    strategy:
      matrix:
        os: [ubuntu-latest,
          # Container action is only supported on Linux
          # macos-latest, windows-latest          
        ]

    runs-on: ${{ matrix.os }}
    name: Run on ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run local bin-local.sh
      shell: bash
      run: bash ./bin-local.sh

    - name: Run this action
      uses: ./
      with:
        input1: lorem
        input2: ipsum
        environment: true
      env:
        FOO: 123
        BAR: 234
